/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_1MHz.h"
#include "HB25_PWM.h"
#include "HB25_PWM_Pin.h"
#include "HB25_PWM_Pin_aliases.h"
#include "HB25_Enable_Pin.h"
#include "HB25_Enable_Pin_aliases.h"
#include "UARTCOMMS.h"
#include "UARTCOMMS_SPI_UART.h"
#include "UARTCOMMS_PINS.h"
#include "UARTCOMMS_SPI_UART_PVT.h"
#include "UARTCOMMS_PVT.h"
#include "UARTCOMMS_BOOT.h"
#include "EZI2C.h"
#include "EZI2C_PINS.h"
#include "EZI2C_PVT.h"
#include "EZI2C_EZI2C.h"
#include "EZI2C_EZI2C_PVT.h"
#include "EZI2C_BOOT.h"
#include "ADC_Infrared.h"
#include "Pin_InfraredDistance_0.h"
#include "Pin_InfraredDistance_0_aliases.h"
#include "Pin_InfraredDistance_1.h"
#include "Pin_InfraredDistance_1_aliases.h"
#include "Pin_InfraredDistance_2.h"
#include "Pin_InfraredDistance_2_aliases.h"
#include "Pin_InfraredDistance_3.h"
#include "Pin_InfraredDistance_3_aliases.h"
#include "Encoder_Pins.h"
#include "Encoder_Pins_aliases.h"
#include "Encoder_Intr.h"
#include "HCSR04_Echo_1.h"
#include "HCSR04_Echo_1_aliases.h"
#include "HCSR04_Echo_2.h"
#include "HCSR04_Echo_2_aliases.h"
#include "HCSR04_Echo_3.h"
#include "HCSR04_Echo_3_aliases.h"
#include "HCSR04_Echo_0.h"
#include "HCSR04_Echo_0_aliases.h"
#include "HCSR04_Timer.h"
#include "HCSR04_Clock.h"
#include "HCSR04_Timeout_Intr.h"
#include "HCSR04_Trigger_0.h"
#include "HCSR04_Trigger_0_aliases.h"
#include "HCSR04_Trigger_2.h"
#include "HCSR04_Trigger_2_aliases.h"
#include "HCSR04_Trigger_3.h"
#include "HCSR04_Trigger_3_aliases.h"
#include "HCSR04_Control.h"
#include "HCSR04_Trigger_1.h"
#include "HCSR04_Trigger_1_aliases.h"
#include "UARTCOMMS_SCBCLK.h"
#include "UARTCOMMS_tx.h"
#include "UARTCOMMS_tx_aliases.h"
#include "UARTCOMMS_rx.h"
#include "UARTCOMMS_rx_aliases.h"
#include "EZI2C_SCBCLK.h"
#include "EZI2C_sda.h"
#include "EZI2C_sda_aliases.h"
#include "EZI2C_scl.h"
#include "EZI2C_scl_aliases.h"
#include "EZI2C_SCB_IRQ.h"
#include "ADC_Infrared_IRQ.h"
#include "ADC_Infrared_intClock.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

